config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :users

  get 'search_product', to: 'products#search'
  get 'search_background', to: 'products#search_background'
  get 'search_results_product', to: 'products#search_results'
  get 'search_results_background', to: 'products#search_results_background'
  get 'clear_cache', to: 'products#clear_cache'

  resources :admins
  get 'sessions/new'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [:get, :delete]
  root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

   validates :search_term, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:admin, :guest]

  validates :username, presence: true, uniqueness: true
  validates :role, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authorize

  private

  def authorize
    if not current_user
      redirect_to login_url
    end
  end

  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end
  helper_method :current_user

end

app/controllers/background_jobs.rb
class BackgroundJobs

  include SuckerPunch::Job
  workers 5

  def perform(search_terms)
    #must set expiration time to sufficient time
    #puts "search terms: " + search_terms.inspect

    Rails.cache.fetch(search_terms, :expires_in => 15.minute) do
      puts "admin accessing API for " + search_terms.inspect
      sem3 = Semantics3::Products.new(SEMANTICS3_API_KEY, SEMANTICS3_API_SECRET)
      sem3.products_field("search", search_terms)
      productsHash = sem3.get_products()
      $products = productsHash["results"]
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

   def index
      @products_all = Product.all.page(params[:page]).per(2)
   end

   def search
   end

   def search_background
   end

   def search_results

      @products = 
        if Rails.cache.fetch(params[:query])
           #puts "option 1"
           Rails.cache.fetch(params[:query])
        elsif !Product.where(search_term: params[:query]).empty?
           search_results = []
           #puts "option 2"
           product_ids = Product.where(search_term: params[:query]).limit(10).pluck(:id)
           products = Product.find(product_ids[0..10])
           products.each do |product|
             search_results  << product.search_results
           end
           search_results
        else
           #puts "option 3"
           get_api_results 
        end

      if @products.class == Array
         @products_paginate = Kaminari.paginate_array(@products).page(params[:page]).per(2) if @products
      else
         @products_paginate = @products.page(params[:page]).per(2) if @products
      end

      if @products
         @products.each do |product|
            if duplicate_product?(product["sem3_id"],product["updated_at"]) == false
               @product = Product.new(allowed_params(params[:query],product))
               @product.save
            end
         end
         render 'search_results'
      else
         flash[:results] = "Search returns no results. Please search again."
         render 'search'
      end

   end

   def search_results_background

     time = 0
     [params[:query1],params[:query2], params[:query3],params[:query4],params[:query5]].each do |job|
       #puts "job: " + job.inspect
       unless job.empty?  
          BackgroundJobs.perform_in(time,job) 
          time += 15
       end
     end

     render 'search_background'
 
   end

   def clear_cache
     Rails.cache.clear 
     redirect_to search_background_path
   end

   private

   def get_api_results
     Rails.cache.fetch(params[:query], :expires_in => 1.minute) do
         #puts "guess accessing API ... search term: " + params[:query].inspect
         sem3 = Semantics3::Products.new(SEMANTICS3_API_KEY, SEMANTICS3_API_SECRET)
         sem3.products_field("search", params[:query])
         productsHash = sem3.get_products()
         if ( (productsHash["message"] != nil) && (productsHash["message"].include?("API key does not exist")))
           flash[:message] = "API key does not exist. Please provide one."
         end
         @products = productsHash["results"]
      end
   end

   def duplicate_product?(sem3_id,updated_at)
     return true if (Product.where('search_results @> ?', {sem3_id: sem3_id, updated_at: updated_at}.to_json).count >= 1)
     false
   end

   def allowed_params(term, results)
      search_term = term
      {search_term: term, search_results: results}
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorize

  def new
  end

 def create
    @user = User.where(username: params[:username]).first
    if @user
      session[:user_id] = @user.id
      case current_user.role
        when "admin"
          redirect_to search_background_path
        when "guest"
          redirect_to search_product_path
      end
    else
      session[:user_id] = nil
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :role)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Semantics3Api</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
   <div class="row">
      <div class="col-xs-12" style="color:#333">
         <% @products_all.each do |product| %>
            <% results = product.search_results %>
            <% results_sorted = results.sort_by{|k,v| k} %>
            <table style="width:100%" class="table-reflow">
            <% results_sorted.each do |k,v| %>
               <% unless k.match('sem3_help') %>
                  <tr>
                     <th><%= k %></th>
                     <td><%= v %></td><br>
                  </tr>
               <% end %>
            <% end %>
            </table>
         <% end %>
         <%= paginate @products_all %>
      </div>
   </div>
</div>

<style>
table, th, td {
   border: 1px solid black;
   border-collapse: collapse;
}
th, td {
   padding: 5px;
   text-align: left;
}
</style>

app/views/products/search.html.erb
<div class="container">
   <div class="row">
      <div class="col-xs-12">

        <h2> Search for Product Information</h2>

        <%= form_tag search_results_product_path, :method=>'get' do %><br>
          <h4> <%= label_tag 'Please enter product to search' %><br> </h4>
          <%= text_field_tag 'query' %>
          <%= submit_tag 'Search' %>
        <% end %><br>
        <h4>
        <% if flash[:message] %> 
           <%= flash[:message] %> 
        <% else %>
           <%= flash[:results] %> 
        <% end %>
        </h4>

      </div>
   </div>
</div>

app/views/products/search_background.html.erb
<div class="container">
   <div class="row">
      <div class="col-xs-12" style="color:#333">

        <h2> Search for Products Information</h2>

        <%= form_tag search_results_background_path, :method=>'get' do %><br>
          <h4> <%= label_tag 'Please enter products to search' %><br> </h4>
          <%= text_field_tag 'query1' %><br>
          <%= text_field_tag 'query2' %><br>
          <%= text_field_tag 'query3' %><br>
          <%= text_field_tag 'query4' %><br>
          <%= text_field_tag 'query5' %><br><br>
          <%= submit_tag 'Prefetch & cache in the backround', class: 'btn btn-primary btn-xs' %>
        <% end %><br>
        <h4>
        <% if flash[:message] %> 
           <%= flash[:message] %> 
        <% else %>
           <%= flash[:results] %> 
        <% end %>
        </h4>

        <%= link_to 'Clear Cached Data', clear_cache_path, class: 'btn btn-primary btn-xs' %>

        <%= link_to 'Log out', 'logout', class: 'btn btn-primary btn-xs' %><br>

      </div>
   </div>
</div>

app/views/products/search_results.html.erb
<div class="container">
   <div class="row">
      <div class="col-xs-12">

        <br>
        <%= link_to 'Search Again', search_product_path, class: 'btn btn-primary btn-xs' %>
        <%= link_to 'Log out', 'logout', class: 'btn btn-primary btn-xs' %><br>
        <br>

        <% @products_paginate.each do |result| %>
        <table style="width:100%" class="table-reflow">
          <% result_sorted = result.sort_by{|k,v| k} %>
          <% result_sorted.each do |key, value| %>
             <tr>
                <th><%= key %></th>
                <td><%= value %></td>
             </tr>
          <% end %>
        </table><br><br>
        <% end %>
        <%= paginate @products_paginate %>
      </div>
   </div>
</div>

<style>
table, th, td {
   border: 1px solid black;
   border-collapse: collapse;
}
th, td {
   padding: 5px;
   text-align: left;
}
</style>

app/views/users/_admin.html.erb
welcome admin!

app/views/users/index.html.erb
<div class="container">
   <div class="rows"> 
      <div class="col-xs-12">
         <% case current_user.role %>
            <% when "admin" %>
               <%= render partial: "admin" %>
            <% when "guest" %>
               <%= render partial: "guest" %>
         <% end %>
               
         <%= link_to 'Log out', 'logout', class: 'btn btn-primary btn-xs' %><br>

      </div>
   </div>
</div>